on:
  workflow_dispatch:
    inputs:
      deployref:
        description: 'Ref to deploy'
        required: true
        default: 'refs/heads/main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.deployref }}
    - uses: shimataro/ssh-key-action@8ddce4efa1dc93160617224cdadf97c23bb3814a # v2.0.3
      with:
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        known_hosts: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
        config: ${{ secrets.DEPLOY_SSH_CONFIG }}
    - name: Deploy to production
      run: |
        echo "Deploying ${{ github.event.inputs.deployref }}"
        #deploy/deploy.sh $GITHUB_WORKSPACE
  